blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/DukeWood/aicmo-newsletter/blob/main/README.md
    about: Read the project documentation and guides
  - name: Discussions
    url: https://github.com/DukeWood/aicmo-newsletter/discussions
    about: Ask questions and discuss ideas with the community
